-- MySQL Script generated by MySQL Workbench
-- sex 13 nov 2020 21:23:25 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `nascimento` DATETIME NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `tipo` INT NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `preco` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `idinventario` INT NOT NULL AUTO_INCREMENT,
  `quantidade` VARCHAR(45) NULL,
  `inventariocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idinventario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genero` (
  `idgenero` INT NOT NULL AUTO_INCREMENT,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`idgenero`, `produto_idproduto`),
  INDEX `fk_genero_produto1_idx` (`produto_idproduto` ASC),
  CONSTRAINT `fk_genero_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`encomenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`encomenda` (
  `usuario_idusuario` INT NOT NULL,
  `inventario_idinventario` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `inventario_idinventario`),
  INDEX `fk_usuario_has_inventario_inventario1_idx` (`inventario_idinventario` ASC),
  INDEX `fk_usuario_has_inventario_usuario_idx` (`usuario_idusuario` ASC),
  CONSTRAINT `fk_usuario_has_inventario_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_inventario_inventario1`
    FOREIGN KEY (`inventario_idinventario`)
    REFERENCES `mydb`.`inventario` (`idinventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `inventario_idinventario` INT NOT NULL,
  `produto_idproduto` INT NOT NULL,
  PRIMARY KEY (`inventario_idinventario`, `produto_idproduto`),
  INDEX `fk_inventario_has_produto_produto1_idx` (`produto_idproduto` ASC),
  INDEX `fk_inventario_has_produto_inventario1_idx` (`inventario_idinventario` ASC),
  CONSTRAINT `fk_inventario_has_produto_inventario1`
    FOREIGN KEY (`inventario_idinventario`)
    REFERENCES `mydb`.`inventario` (`idinventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_has_produto_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
