-- MySQL Script generated by MySQL Workbench
-- Sat Nov 28 22:18:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `valor` FLOAT NOT NULL,
  `descricao` TEXT NOT NULL,
  `genero` VARCHAR(60) NOT NULL,
  `classificacao` INT NOT NULL,
  `plataforma` VARCHAR(60) NOT NULL,
  `lancamento` DATE NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plataforma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plataforma` (
  `idplataforma` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` FLOAT NOT NULL,
  `lancamento` DATE NOT NULL,
  `descricao` TEXT NOT NULL,
  PRIMARY KEY (`idplataforma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inventario` (
  `idinventario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `aquisicao` DATE NOT NULL,
  `produto_idproduto` INT NOT NULL,
  `valor` FLOAT NOT NULL,
  `plataforma_idplataforma` INT NOT NULL,
  PRIMARY KEY (`idinventario`, `produto_idproduto`, `plataforma_idplataforma`),
  INDEX `fk_inventario_produto1_idx` (`produto_idproduto` ASC),
  INDEX `fk_inventario_plataforma1_idx` (`plataforma_idplataforma` ASC),
  CONSTRAINT `fk_inventario_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_plataforma1`
    FOREIGN KEY (`plataforma_idplataforma`)
    REFERENCES `mydb`.`plataforma` (`idplataforma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `nascimento` DATE NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(150) NOT NULL,
  `tipo` INT NOT NULL,
  `endereco` VARCHAR(80) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `produto_idproduto` INT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `plataforma_idplataforma` INT NOT NULL,
  `dataPedido` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `dataEntrega` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpedido`, `produto_idproduto`, `usuario_idusuario`, `plataforma_idplataforma`),
  INDEX `fk_pedido_produto1_idx` (`produto_idproduto` ASC),
  INDEX `fk_pedido_usuario1_idx` (`usuario_idusuario` ASC),
  INDEX `fk_pedido_plataforma1_idx` (`plataforma_idplataforma` ASC),
  CONSTRAINT `fk_pedido_produto1`
    FOREIGN KEY (`produto_idproduto`)
    REFERENCES `mydb`.`produto` (`idproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_plataforma1`
    FOREIGN KEY (`plataforma_idplataforma`)
    REFERENCES `mydb`.`plataforma` (`idplataforma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
